### ISSUE TITLE
add tests to check missionsCompleted7Days value is in required range

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/missioncontrol#31] opened 2017-08-23 14:06 UTC
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for writing code that makes drones fly, lets cars find charging stations, helps people and goods get from place to place, and more.

Find more **first-timers-only** issues here:
- [Missions](https://github.com/DAVFoundation/missions/labels/first-timers-only)
- [Mission Control](https://github.com/DAVFoundation/missioncontrol/labels/first-timers-only)
- [Captain](https://github.com/DAVFoundation/captain/labels/first-timers-only)

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Mission Control

The DAV project you are looking at is *Mission Control*. It is the brain in charge of orchestrating missions between DAV users and autonomous vehicles.

### Background

To help developers building on top of DAV technologies, Mission Control can start in a simulation environment. In a simulation environment, there are always a few simulated drones flying around the user, ready to take on missions. This makes it easy for developers to start building and testing without investing in hardware.

### The Issue

As a project that relies on a large community of contributors, it is very important for us to have good tests to make sure changes don't break anything.

One of the functions that need testing is  `randomMissionsCompleted()` inside [/server/simulation/random.js](https://github.com/DAVFoundation/missioncontrol/blob/master/server/simulation/random.js)  that creates random number of `missionsCompleted` and `missionsCompleted7Days`. 

The task for this issue is to test the functions return value.
- **missionsCompleted7Days** should be **a positive integer that is less than or equal to the value of missionsCompleted**

Edit `test/specs/simulation.random.spec.js`, adding a `describe` block for `randomMissionsCompleted()` if it does not exists and within it one test that verify the condition mentioned above.

To run your tests, run `npm test` from the project's root directory. All tests should pass.

![tests](https://user-images.githubusercontent.com/926653/29587147-af5495ce-8795-11e7-9e80-09089d03251b.gif)

### Contributing to Mission Control

- [ ] Fork the repository from the [Mission Control GitHub page](https://github.com/DAVFoundation/missioncontrol).
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/missioncontrol.git`
- [ ] Make sure you have _node.js_ and _npm_ installed on your machine. You can use this [guide](https://docs.npmjs.com/getting-started/installing-node) for help.
- [ ] Install all of the project's dependencies with npm. `$ cd missioncontrol; npm install`
- [ ] Run `npm test` to run linting checks and all the automated tests and see that they pass.
- [ ] **Code! code! code!**
- [ ] Before committing your code, run `npm test` one last time and make sure no errors (including linting errors) are thrown.
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/missioncontrol](https://github.com/YOUR-USER-NAME/missioncontrol)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#30`)

**Comment by TalAter** [comment] 2017-08-23 20:10
# This issue is still available for first-time contributors
**The commits listed above this message are for a different issue**

**Comment by sblasa** [comment] 2017-09-01 04:12
@TalAter @cg-cnu  Hi, I would like to try help with this one if that's okay.

**Comment by TalAter** [comment] 2017-09-01 09:49
Go for it @sblasa!

Thank you 🙇

**Comment by sblasa** [comment] 2017-09-03 01:33
@TalAter Thanks! 😄

**Comment by TalAter** [comment] 2017-09-12 09:00
Hey @sblasa, how is it going with this one? Do you need any help with it?

**Comment by sblasa** [comment] 2017-09-13 14:49
@TalAter Hi! Sorry, got busy with work. Starting on it today.

**Comment by sblasa** [comment] 2017-09-13 15:15
@TalAter I'm getting this error when I run the npm test. I followed directions noted above description.

C:\Users\stbla\code_school\opensource\missioncontrol [master ≡ +0 ~2 -0 !]> npm test

> missioncontrol@0.0.1 test C:\Users\stbla\code_school\opensource\missioncontrol
> gulp jest

[08:12:49] Using gulpfile ~\code_school\opensource\missioncontrol\gulpfile.js
[08:12:49] Starting 'jest'...
C:\Users\stbla\code_school\opensource\missioncontrol\node_modules\jest-haste-map\build\crawlers\node.js:36
      names.forEach(file => {
           ^

TypeError: Cannot read property 'forEach' of undefined
    at fs.readdir (C:\Users\stbla\code_school\opensource\missioncontrol\node_modules\jest-haste-map\build\crawlers\node.js:36:12)
    at go$readdir$cb (C:\Users\stbla\code_school\opensource\missioncontrol\node_modules\jest-cli\node_modules\graceful-fs\graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! Test failed.  See above for more details.

**Comment by TalAter** [comment] 2017-09-13 16:29
Hmmm. I cannot reproduce this on my machine and there is nothing specific about Mission Control code in the error.

My guess would be it has something to do with the script trying to access the filesystem in an environment that isn't *unix-like*.

Are you using the standard/old school command shell of Windows? If you are using Windows 10, I would try using the new bash-like shell they offer. If you are in an older version I know I used to use cygwin back in my Windows days, but there may be better solutions these days.

I know this may seem like a lot of hoops to jump for just to send a PR for this project, but I think it is worth it because this has far reaching consequences for most open source projects you'll work with.

**Comment by sblasa** [comment] 2017-09-14 16:27
@TalAter Hi, yes, I tried using Git Bash, and that didn't work as well. I'm going to redo the repo on my machine and run it again. I will keep trying! :) Thanks!

**Comment by sblasa** [comment] 2017-09-16 20:51
@TalAter Hi, I figured out that I needed to do a pull from the original repo and merge it with my project. I had noticed that there were some file changes in the original missioncontrol that I didn't have. It's working now. Moving on to fix the issue at hand. :)

**Comment by sblasa** [comment] 2017-09-25 03:50
@TalAter , so I'm looking at the est/specs/simulation.random.spec.js . There is a describe block in there already, but I needed some help. I added the test in bold below and it passed. However, I need to add a test to see if the missionsCompleted7Days is a positive integer. Could you tell me how I could add that to the test? 

Thanks!

describe('randomMissionsCompleted()', () => {

  test('returns an object', () => {
    expect(
      typeof randomMissionsCompleted()
    ).toBe('object');
  });

  **test('returns an object containing missionsCompleted7Days which is less than or equal to missionsCompleted', () => {
      expect(
        randomMissionsCompleted().missionsCompleted7Days
      ).toBeLessThanOrEqual(randomMissionsCompleted().missionsCompleted);
  });**

  test('returns an object containing missionsCompleted which is an integer between 4 and 90', () => {
    expect(
      Number.isInteger(randomMissionsCompleted().missionsCompleted)
    ).toBeTruthy();
    expect(
      randomMissionsCompleted().missionsCompleted
    ).toBeLessThanOrEqual(90);
    expect(
      randomMissionsCompleted().missionsCompleted
    ).toBeGreaterThanOrEqual(4);
  });

});

**Comment by Rob-Rychs** [comment] 2017-09-25 04:18
Hey @sblasa,
Maybe try something like `.toBeGreaterThan(0)` ?
That will at least check to make sure it's a positive number, if not a whole number which I'm not sure is necessary to test for
https://facebook.github.io/jest/docs/en/expect.html#tobegreaterthannumber
Just my thoughts... 
😃

**Comment by TalAter** [comment] 2017-09-25 10:41
Thanks @Rob-Rychs 

@sblasa does that answer your question?

GitHub Pro Tip #3704: When entering code in these GitHub issues, it is best to use markdown to make it easier to read... You even get syntax highlighting for free with it:

Just surround your code with some backticks like so:

```javascript
describe('randomMissionsCompleted()', () => {

  test('returns an object', () => {
    expect(
      typeof randomMissionsCompleted()
    ).toBe('object');
  });

});
```

<img width="642" alt="add_tests_to_check_missionscompleted7days_value_is_in_required_range_ _issue__31_ _davfoundation_missioncontrol" src="https://user-images.githubusercontent.com/926653/30804746-d87c0810-a1ee-11e7-95c6-d55f413fb1c9.png">

**Comment by sblasa** [comment] 2017-09-25 14:51
@TalAter Ah, thanks for the tip! I was wondering how I would do that. 👍  I'm going to try out the code that Rob-Rychs mentioned.
@Rob-Rychs thank you for your help! I will try that and see if it works. 👍

**Comment by sblasa** [comment] 2017-09-27 03:50
@TalAter The code passed when I ran the test. I added this code
```javascript
test('returns an object containing missionsCompleted7Days which is less than or equal to missionsCompleted', () => {
      expect(
        randomMissionsCompleted().missionsCompleted7Days
      ).toBeLessThanOrEqual(randomMissionsCompleted().missionsCompleted);
  
  });

  test('returns an object containing missionsCompleted7Days which is an integer', () => {      
      expect(
        Number.isInteger(randomMissionsCompleted().missionsCompleted7Days)
      ).toBeTruthy();     
  
  });

  test('returns an object containing missionsCompleted7Days which is a positive number', () => {     
      expect(
        randomMissionsCompleted().missionsCompleted7Days
      ).toBeGreaterThan(0);

  });
```

What do you think? Thanks for your help!

**Comment by TalAter** [comment] 2017-09-27 22:05
- The following is just a stylistic choice, but I think we should stick to the same format of test someone has already written for `missionsCompleted` (https://github.com/DAVFoundation/missioncontrol/blob/master/test/specs/simulation.random.spec.js#L43), which is to include all of them in one test that asserts that "missionsCompleted7Days should be a positive integer that is less than or equal to the value of missionsCompleted".

- I would replace the condition `toBeTruthy()` with a more strict `toBe(true)`. [toBeTruthy](https://facebook.github.io/jest/docs/en/expect.html#tobetruthy) would pass on anything that is truthy (e.g. `true`, `17.3`, `"Esmarelda Villalobos"`). This shouldn't be a problem here, since `Number.isInteger` always returns a boolean... but why not be more strict when we can? 😃

- Your first test might fail from time to time because you are calling randomMissionsCompleted() twice. We want to verify that each time we call it, it will contain a `missionsCompleted7Days` that is smaller than the `missionsCompleted` it returned this time. But since you call it twice, you might get `{missionsCompleted7Days: 2, missionsCompleted: 4}` the first time you call it, and `{missionsCompleted7Days: 10, missionsCompleted: 100}` the second time which would fail your test  (10 < 4) even though it satisfied the requirement we want to test (10 < 100)

**Comment by Rob-Rychs** [comment] 2017-09-27 22:30
Good stuff @sblasa @TalAter 
If we store the original call to missionsCompleted() and then run the test using the properties from the stored call that might help prevent the issue with it failing from time to time... 
something like...
 ```JS 
test('returns an object containing missionsCompleted7Days which is less than or equal to missionsCompleted', () => {
    const prop = randomMissionsCompleted();
    expect(
      prop.missionsCompleted7Days
    ).toBeLessThanOrEqual(prop.missionsCompleted);

  }); `

**Comment by TalAter** [comment] 2017-10-08 11:34
@sblasa Are you still interested in working on this issue? We have received another pull request for it by @JordanShaak

**Comment by sblasa** [comment] 2017-10-08 16:45
@TalAter @Rob-Rychs Yes, I finished the update yesterday, and I was just going back through steps on Pull Request. I am submitting the pull request.  Thanks! :)

**Comment by TalAter** [comment] 2017-10-09 14:56
🎊 Just merged it. Awesome!

Congratulations on being an open sourcerer, and thank you so much for taking the time to help build the project!

**Closed by TalAter** 2017-10-09 14:56 UTC
Labels: claimed, first-timers-only

**Comment by sblasa** [comment] 2017-10-09 14:59
@TalAter @Rob-Rychs Thanks for all your help! I'll keep an eye out for any other issues that I can help with. :)
