### ISSUE TITLE
not able to retreive vehicle from redis store using id

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/missioncontrol#162] opened 2018-02-16 18:50 UTC
## Expected Behavior
Mission control should return vehicles 

## Current Behavior
Docker instance started with out errors and on loading missions I got this error

```
missioncontrol_1  | Thrift server started. Listening on port 9090
missioncontrol_1  | Web server started. Listening on port 8443
missioncontrol_1  | (node:53) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'long' of null
missioncontrol_1  |     at getVehicle (/app/server/store/vehicles.js:42:35)
missioncontrol_1  |     at <anonymous>
missioncontrol_1  |     at process._tickCallback (internal/process/next_tick.js:160:7)
missioncontrol_1  | (node:53) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
missioncontrol_1  | (node:53) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Steps to Reproduce (for bugs)

1. start missioncontrol as mentioned in contributing.md
2. Start missions

## Your Environment

* Version used:
* Environment name and version (e.g. Node 7.3.12): node 9.5.0
* Server type and version:
* Operating System and version: 
* Link to your project:

**Comment by TalAter** [comment] 2018-02-17 17:50
I'm guessing this isn't enough to reproduce it, as it has been working for us lately.

@cg-cnu Can you make sure you have the latest version, and that the error still happens, and if so try and fix it maybe? Or help us reproduce it?

**Comment by cg-cnu** [comment] 2018-02-17 19:15
Hey @TalAter Seems like a strange one off issue. 
I pasted the whole output from docker below.
One warning I ignored before is about Transperent Huge Pages(THP). 
Found respective issue about it https://github.com/antirez/redis/issues/3895 and realized its not a critical one. 

While I look into more details of this one and other potential issues. Can you confirm if you guys get this warning ? 

```
redis uses an image, skipping
Building missioncontrol
Step 1/7 : FROM node:9.3.0-alpine
 ---> cee518159787
Step 2/7 : COPY package.json /app/
 ---> Using cache
 ---> eb6c2f68f420
Step 3/7 : WORKDIR /app
 ---> Using cache
 ---> ee3e8ded2280
Step 4/7 : RUN npm install
 ---> Using cache
 ---> f0f1cb417fd7
Step 5/7 : RUN npm install -g nodemon
 ---> Using cache
 ---> c6a7e6571cf7
Step 6/7 : COPY . /app
 ---> 9314f75af799
Step 7/7 : CMD [ "npm", "start" ]
 ---> Running in 0a48f899601f
Removing intermediate container 0a48f899601f
 ---> 77716c7cccac
Successfully built 77716c7cccac
Successfully tagged missioncontrol_missioncontrol:latest
Starting missioncontrol_redis_1 ... done
Recreating missioncontrol_missioncontrol_1 ... done
Attaching to missioncontrol_redis_1, missioncontrol_missioncontrol_1
redis_1           | 1:C 17 Feb 19:01:11.701 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1           | 1:C 17 Feb 19:01:11.703 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1           | 1:C 17 Feb 19:01:11.704 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1           | 1:M 17 Feb 19:01:11.707 * Running mode=standalone, port=6379.
redis_1           | 1:M 17 Feb 19:01:11.707 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1           | 1:M 17 Feb 19:01:11.707 # Server initialized
redis_1           | 1:M 17 Feb 19:01:11.707 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1           | 1:M 17 Feb 19:01:11.713 * DB loaded from disk: 0.005 seconds
redis_1           | 1:M 17 Feb 19:01:11.713 * Ready to accept connections
missioncontrol_1  | [nodemon] 1.15.0
missioncontrol_1  | [nodemon] to restart at any time, enter `rs`
missioncontrol_1  | [nodemon] watching: *.*
missioncontrol_1  | [nodemon] starting `node server/start-servers.js`
missioncontrol_1  | Thrift server started. Listening on port 9090
missioncontrol_1  | Web server started. Listening on port 8443


missioncontrol_1  | (node:17) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'long' of null
missioncontrol_1  |     at getVehicle (/app/server/store/vehicles.js:42:35)
missioncontrol_1  |     at <anonymous>
missioncontrol_1  |     at process._tickCallback (internal/process/next_tick.js:160:7)
missioncontrol_1  | (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
missioncontrol_1  | (node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by TalAter** [comment] 2018-02-17 19:35
I was able to recreate the issue you mentioned, and it can be fixed by flushing Redis. This is because we changed the structure of the data we store.

````shell
docker exec -it missioncontrol_redis_1 redis-cli FLUSHALL
````

**Comment by cg-cnu** [comment] 2018-02-17 19:39
Thanks much! Finally my drones are up 😄 
![](https://user-images.githubusercontent.com/2767425/36344955-3e7850da-1448-11e8-9093-4a68863c8ffa.png)

**Comment by cg-cnu** [comment] 2018-02-27 18:16
Hey @TalAter I faced this issue again and I noticed someone else faced it in the gitter channel as well. Is it something we should do regularly ? if so can we add it to contributig.md ?

**Comment by TalAter** [comment] 2018-02-27 20:55
Did flushing redis help you this time?

I think it might be a good idea to add it to the CONTRIBUTING:

Having trouble? Make sure you've pulled the latest changes from both Mission Control and Missions, and run the command ... to clear the Redis cache.

**Comment by srfrnk** [comment] 2018-02-28 08:00
I think this is a symptom for a larger problem.
Can we maybe leave it open and try to trace the steps to reproduce?

**Comment by cg-cnu** [comment] 2018-02-28 17:58
Hey @TalAter Yes, flusing redis fixed the issue. So, for now am adding this to contributing. 

Hey @srfrnk am reopening this issue as a reminder. Feel free to close if you thinks the issues is taken care of.

**Comment by gabimoncha** [comment] 2018-03-05 20:50
I am also getting the same message when `sudo docker-compose build && sudo docker-compose`
```
redis uses an image, skipping
Building missioncontrol
Step 1/7 : FROM node:9.3.0-alpine
 ---> cee518159787
Step 2/7 : COPY package.json /app/
 ---> Using cache
 ---> 7492e59ae473
Step 3/7 : WORKDIR /app
 ---> Using cache
 ---> bc4199149c52
Step 4/7 : RUN npm install
 ---> Using cache
 ---> ea81caf43721
Step 5/7 : RUN npm install -g nodemon
 ---> Using cache
 ---> 4483fa52d0b0
Step 6/7 : COPY . /app
 ---> Using cache
 ---> 07dd238ee702
Step 7/7 : CMD npm start
 ---> Using cache
 ---> 82c90d39ad61
Successfully built 82c90d39ad61
Starting missioncontrol_redis_1
Starting missioncontrol_missioncontrol_1
Attaching to missioncontrol_redis_1, missioncontrol_missioncontrol_1
redis_1           | 1:C 05 Mar 20:48:57.238 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1           | 1:C 05 Mar 20:48:57.238 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1           | 1:C 05 Mar 20:48:57.238 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1           | 1:M 05 Mar 20:48:57.239 * Running mode=standalone, port=6379.
redis_1           | 1:M 05 Mar 20:48:57.239 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1           | 1:M 05 Mar 20:48:57.239 # Server initialized
redis_1           | 1:M 05 Mar 20:48:57.239 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1           | 1:M 05 Mar 20:48:57.239 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1           | 1:M 05 Mar 20:48:57.245 * DB loaded from disk: 0.006 seconds
redis_1           | 1:M 05 Mar 20:48:57.245 * Ready to accept connections
missioncontrol_1  | [nodemon] 1.17.1
missioncontrol_1  | [nodemon] to restart at any time, enter `rs`
missioncontrol_1  | [nodemon] watching: *.*
missioncontrol_1  | [nodemon] starting `node server/start-servers.js`
missioncontrol_1  | Thrift server started. Listening on port 9090
missioncontrol_1  | Web server started. Listening on port 8443
```

**Comment by srfrnk** [comment] 2018-03-06 06:35
@gabimoncha Thanks for the input. This is a warning and since this is just a development environment not critical. If this were to show in production I'd be worried.

@cg-cnu - Thanks for reopening.

**Closed** 2018-03-08 14:05 UTC
